kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          command:
            - /opt/go/netpol-gatekeeper
          args:
            - "--zap-log-level={{ .Values.logger.level }}"
            - "--leader-elect"
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: health-probe
            - containerPort: 9443
              name: webhook
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: "webhook-certs"
              readOnly: true
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: "webhook-certs"
          secret:
            defaultMode: 420
            secretName: {{ .Values.name }}-certs
