apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-netpol
  namespace: {{ .Release.Namespace }}
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: Cg==
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ .Values.name }}
        path: /validate-netpol
    failurePolicy: Fail
    name: validate-netpol-webhook.example.com
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        operations:
          - DELETE
        resources:
          - networkpolicies
    sideEffects: None
