name: netpol-gatekeeper

logger:
  level: info

image: quay.io/rlourencc/netpol-gatekeeper:test

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
